export enum NotificationType {
    HAPPENSINAMINUTE = "HAPPENSINAMINUTE",
    HAPPENSINTWENTYSECONDS = "HAPPENSINTWENTYSECONDS",
    COUNTDOWNSTARTS = "COUNTDOWNSTARTS",
    TRIGGERED = "TRIGGERED",
    ENDED = "ENDED"
  }